name: Keep the repo alive
on:
  schedule:
    - cron: "48 18 * * *"
  push:
  fork:
  status:
  issues:

permissions:
  contents: write

jobs:
  keep_alive:
    name: Keep the repo alive & active
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
          committer_username: ${{ github.repository_owner }}
          committer_email: ${{ github.repository_owner }}@users.noreply.github.com